services:
  - type: web
    name: shl-api-backend
    env: python
    plan: free
    buildCommand: ""
    startCommand: python -m uvicorn api:app --host 0.0.0.0 --port $PORT
    workingDir: src
    envVars:
      - key: PYTHON_VERSION
        value: 3.10
